<table>
	<tr>
		<th>Environment Variable</th>
		<th>Value</th>
	</tr>
	<tr>
		<td>contentSpaceId</td>
		<td>$contentSpaceId.getData()</td>
	</tr>
	<tr>
		<td>documentId</td>
		<td>$documentId.getData()</td>
	</tr>
	<tr>
		<td>folderId</td>
		<td>$folderId.getData()</td>
	</tr>
	<tr>
		<td>formId</td>
		<td>$formId.getData()</td>
	</tr>
	<tr>
		<td>organizationId</td>
		<td>$organizationId.getData()</td>
	</tr>
	<tr>
		<td>roleId</td>
		<td>$roleId.getData()</td>
	</tr>
	<tr>
		<td>structureId</td>
		<td>$structureId.getData()</td>
	</tr>
	<tr>
		<td>structuredContentId</td>
		<td>$structuredContentId.getData()</td>
	</tr>
	<tr>
		<td>userId</td>
		<td>$userId.getData()</td>
	</tr>
</table>

<p>
	<a href="$postmanEnvironmentPropertiesDocument.getData()"> $languageUtil.format($locale, "download-x", "Environment Properties", false) </a>
</p>