/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.modern.site.building.fragment.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.modern.site.building.fragment.model.MSBFragmentEntry;
import com.liferay.modern.site.building.fragment.service.MSBFragmentEntryLocalService;
import com.liferay.modern.site.building.fragment.service.persistence.MSBFragmentCollectionPersistence;
import com.liferay.modern.site.building.fragment.service.persistence.MSBFragmentEntryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the msb fragment entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.modern.site.building.fragment.service.impl.MSBFragmentEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.modern.site.building.fragment.service.impl.MSBFragmentEntryLocalServiceImpl
 * @see com.liferay.modern.site.building.fragment.service.MSBFragmentEntryLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class MSBFragmentEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MSBFragmentEntryLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.modern.site.building.fragment.service.MSBFragmentEntryLocalServiceUtil} to access the msb fragment entry local service.
	 */

	/**
	 * Adds the msb fragment entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param msbFragmentEntry the msb fragment entry
	 * @return the msb fragment entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MSBFragmentEntry addMSBFragmentEntry(
		MSBFragmentEntry msbFragmentEntry) {
		msbFragmentEntry.setNew(true);

		return msbFragmentEntryPersistence.update(msbFragmentEntry);
	}

	/**
	 * Creates a new msb fragment entry with the primary key. Does not add the msb fragment entry to the database.
	 *
	 * @param msbFragmentEntryId the primary key for the new msb fragment entry
	 * @return the new msb fragment entry
	 */
	@Override
	public MSBFragmentEntry createMSBFragmentEntry(long msbFragmentEntryId) {
		return msbFragmentEntryPersistence.create(msbFragmentEntryId);
	}

	/**
	 * Deletes the msb fragment entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param msbFragmentEntryId the primary key of the msb fragment entry
	 * @return the msb fragment entry that was removed
	 * @throws PortalException if a msb fragment entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MSBFragmentEntry deleteMSBFragmentEntry(long msbFragmentEntryId)
		throws PortalException {
		return msbFragmentEntryPersistence.remove(msbFragmentEntryId);
	}

	/**
	 * Deletes the msb fragment entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param msbFragmentEntry the msb fragment entry
	 * @return the msb fragment entry that was removed
	 * @throws PortalException
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MSBFragmentEntry deleteMSBFragmentEntry(
		MSBFragmentEntry msbFragmentEntry) throws PortalException {
		return msbFragmentEntryPersistence.remove(msbFragmentEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MSBFragmentEntry.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return msbFragmentEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.modern.site.building.fragment.model.impl.MSBFragmentEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return msbFragmentEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.modern.site.building.fragment.model.impl.MSBFragmentEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return msbFragmentEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return msbFragmentEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return msbFragmentEntryPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public MSBFragmentEntry fetchMSBFragmentEntry(long msbFragmentEntryId) {
		return msbFragmentEntryPersistence.fetchByPrimaryKey(msbFragmentEntryId);
	}

	/**
	 * Returns the msb fragment entry with the primary key.
	 *
	 * @param msbFragmentEntryId the primary key of the msb fragment entry
	 * @return the msb fragment entry
	 * @throws PortalException if a msb fragment entry with the primary key could not be found
	 */
	@Override
	public MSBFragmentEntry getMSBFragmentEntry(long msbFragmentEntryId)
		throws PortalException {
		return msbFragmentEntryPersistence.findByPrimaryKey(msbFragmentEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(msbFragmentEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MSBFragmentEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("msbFragmentEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(msbFragmentEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MSBFragmentEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"msbFragmentEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(msbFragmentEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MSBFragmentEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("msbFragmentEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return msbFragmentEntryLocalService.deleteMSBFragmentEntry((MSBFragmentEntry)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return msbFragmentEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the msb fragment entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.modern.site.building.fragment.model.impl.MSBFragmentEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of msb fragment entries
	 * @param end the upper bound of the range of msb fragment entries (not inclusive)
	 * @return the range of msb fragment entries
	 */
	@Override
	public List<MSBFragmentEntry> getMSBFragmentEntries(int start, int end) {
		return msbFragmentEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of msb fragment entries.
	 *
	 * @return the number of msb fragment entries
	 */
	@Override
	public int getMSBFragmentEntriesCount() {
		return msbFragmentEntryPersistence.countAll();
	}

	/**
	 * Updates the msb fragment entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param msbFragmentEntry the msb fragment entry
	 * @return the msb fragment entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MSBFragmentEntry updateMSBFragmentEntry(
		MSBFragmentEntry msbFragmentEntry) {
		return msbFragmentEntryPersistence.update(msbFragmentEntry);
	}

	/**
	 * Returns the msb fragment entry local service.
	 *
	 * @return the msb fragment entry local service
	 */
	public MSBFragmentEntryLocalService getMSBFragmentEntryLocalService() {
		return msbFragmentEntryLocalService;
	}

	/**
	 * Sets the msb fragment entry local service.
	 *
	 * @param msbFragmentEntryLocalService the msb fragment entry local service
	 */
	public void setMSBFragmentEntryLocalService(
		MSBFragmentEntryLocalService msbFragmentEntryLocalService) {
		this.msbFragmentEntryLocalService = msbFragmentEntryLocalService;
	}

	/**
	 * Returns the msb fragment entry persistence.
	 *
	 * @return the msb fragment entry persistence
	 */
	public MSBFragmentEntryPersistence getMSBFragmentEntryPersistence() {
		return msbFragmentEntryPersistence;
	}

	/**
	 * Sets the msb fragment entry persistence.
	 *
	 * @param msbFragmentEntryPersistence the msb fragment entry persistence
	 */
	public void setMSBFragmentEntryPersistence(
		MSBFragmentEntryPersistence msbFragmentEntryPersistence) {
		this.msbFragmentEntryPersistence = msbFragmentEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the msb fragment collection local service.
	 *
	 * @return the msb fragment collection local service
	 */
	public com.liferay.modern.site.building.fragment.service.MSBFragmentCollectionLocalService getMSBFragmentCollectionLocalService() {
		return msbFragmentCollectionLocalService;
	}

	/**
	 * Sets the msb fragment collection local service.
	 *
	 * @param msbFragmentCollectionLocalService the msb fragment collection local service
	 */
	public void setMSBFragmentCollectionLocalService(
		com.liferay.modern.site.building.fragment.service.MSBFragmentCollectionLocalService msbFragmentCollectionLocalService) {
		this.msbFragmentCollectionLocalService = msbFragmentCollectionLocalService;
	}

	/**
	 * Returns the msb fragment collection persistence.
	 *
	 * @return the msb fragment collection persistence
	 */
	public MSBFragmentCollectionPersistence getMSBFragmentCollectionPersistence() {
		return msbFragmentCollectionPersistence;
	}

	/**
	 * Sets the msb fragment collection persistence.
	 *
	 * @param msbFragmentCollectionPersistence the msb fragment collection persistence
	 */
	public void setMSBFragmentCollectionPersistence(
		MSBFragmentCollectionPersistence msbFragmentCollectionPersistence) {
		this.msbFragmentCollectionPersistence = msbFragmentCollectionPersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.modern.site.building.fragment.model.MSBFragmentEntry",
			msbFragmentEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.modern.site.building.fragment.model.MSBFragmentEntry");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MSBFragmentEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MSBFragmentEntry.class;
	}

	protected String getModelClassName() {
		return MSBFragmentEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = msbFragmentEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MSBFragmentEntryLocalService.class)
	protected MSBFragmentEntryLocalService msbFragmentEntryLocalService;
	@BeanReference(type = MSBFragmentEntryPersistence.class)
	protected MSBFragmentEntryPersistence msbFragmentEntryPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.modern.site.building.fragment.service.MSBFragmentCollectionLocalService.class)
	protected com.liferay.modern.site.building.fragment.service.MSBFragmentCollectionLocalService msbFragmentCollectionLocalService;
	@BeanReference(type = MSBFragmentCollectionPersistence.class)
	protected MSBFragmentCollectionPersistence msbFragmentCollectionPersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}