create table WorkflowMetricsSLADefinition (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	workflowMetricsSLADefinitionId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	name STRING null,
	description TEXT null,
	duration LONG,
	calendarKey VARCHAR(75) null,
	processId LONG,
	processVersion VARCHAR(75) null,
	pauseNodeKeys VARCHAR(75) null,
	startNodeKeys VARCHAR(75) null,
	stopNodeKeys VARCHAR(75) null,
	status INTEGER
);