/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.uad.anonymizer;

import com.liferay.change.tracking.model.CTCollection;
import com.liferay.change.tracking.service.CTCollectionLocalService;
import com.liferay.change.tracking.uad.constants.CTUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the ct collection UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link CTCollectionUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseCTCollectionUADAnonymizer
	extends DynamicQueryUADAnonymizer<CTCollection> {

	@Override
	public void autoAnonymize(
			CTCollection ctCollection, long userId, User anonymousUser)
		throws PortalException {

		if (ctCollection.getUserId() == userId) {
			ctCollection.setUserId(anonymousUser.getUserId());
			ctCollection.setUserName(anonymousUser.getFullName());
		}

		if (ctCollection.getStatusByUserId() == userId) {
			ctCollection.setStatusByUserId(anonymousUser.getUserId());
			ctCollection.setStatusByUserName(anonymousUser.getFullName());
		}

		ctCollectionLocalService.updateCTCollection(ctCollection);
	}

	@Override
	public void delete(CTCollection ctCollection) throws PortalException {
		ctCollectionLocalService.deleteCTCollection(ctCollection);
	}

	@Override
	public Class<CTCollection> getTypeClass() {
		return CTCollection.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return ctCollectionLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return CTUADConstants.USER_ID_FIELD_NAMES_CT_COLLECTION;
	}

	@Reference
	protected CTCollectionLocalService ctCollectionLocalService;

}