/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.batch.engine.service.base;

import com.liferay.batch.engine.model.BatchFileImport;
import com.liferay.batch.engine.service.BatchFileImportLocalService;
import com.liferay.batch.engine.service.persistence.BatchFileImportPersistence;
import com.liferay.batch.engine.service.persistence.BatchJobExecutionPersistence;
import com.liferay.batch.engine.service.persistence.BatchJobInstancePersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.annotation.versioning.ProviderType;

/**
 * Provides the base implementation for the batch file import local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.batch.engine.service.impl.BatchFileImportLocalServiceImpl}.
 * </p>
 *
 * @author Ivica Cardic
 * @see com.liferay.batch.engine.service.impl.BatchFileImportLocalServiceImpl
 * @generated
 */
@ProviderType
public abstract class BatchFileImportLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements BatchFileImportLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>BatchFileImportLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.batch.engine.service.BatchFileImportLocalServiceUtil</code>.
	 */

	/**
	 * Adds the batch file import to the database. Also notifies the appropriate model listeners.
	 *
	 * @param batchFileImport the batch file import
	 * @return the batch file import that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BatchFileImport addBatchFileImport(BatchFileImport batchFileImport) {
		batchFileImport.setNew(true);

		return batchFileImportPersistence.update(batchFileImport);
	}

	/**
	 * Creates a new batch file import with the primary key. Does not add the batch file import to the database.
	 *
	 * @param batchFileImportId the primary key for the new batch file import
	 * @return the new batch file import
	 */
	@Override
	@Transactional(enabled = false)
	public BatchFileImport createBatchFileImport(long batchFileImportId) {
		return batchFileImportPersistence.create(batchFileImportId);
	}

	/**
	 * Deletes the batch file import with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param batchFileImportId the primary key of the batch file import
	 * @return the batch file import that was removed
	 * @throws PortalException if a batch file import with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BatchFileImport deleteBatchFileImport(long batchFileImportId)
		throws PortalException {

		return batchFileImportPersistence.remove(batchFileImportId);
	}

	/**
	 * Deletes the batch file import from the database. Also notifies the appropriate model listeners.
	 *
	 * @param batchFileImport the batch file import
	 * @return the batch file import that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public BatchFileImport deleteBatchFileImport(
		BatchFileImport batchFileImport) {

		return batchFileImportPersistence.remove(batchFileImport);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			BatchFileImport.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return batchFileImportPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.batch.engine.model.impl.BatchFileImportModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return batchFileImportPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.batch.engine.model.impl.BatchFileImportModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return batchFileImportPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return batchFileImportPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return batchFileImportPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public BatchFileImport fetchBatchFileImport(long batchFileImportId) {
		return batchFileImportPersistence.fetchByPrimaryKey(batchFileImportId);
	}

	/**
	 * Returns the batch file import with the matching UUID and company.
	 *
	 * @param uuid the batch file import's UUID
	 * @param companyId the primary key of the company
	 * @return the matching batch file import, or <code>null</code> if a matching batch file import could not be found
	 */
	@Override
	public BatchFileImport fetchBatchFileImportByUuidAndCompanyId(
		String uuid, long companyId) {

		return batchFileImportPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the batch file import with the primary key.
	 *
	 * @param batchFileImportId the primary key of the batch file import
	 * @return the batch file import
	 * @throws PortalException if a batch file import with the primary key could not be found
	 */
	@Override
	public BatchFileImport getBatchFileImport(long batchFileImportId)
		throws PortalException {

		return batchFileImportPersistence.findByPrimaryKey(batchFileImportId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(batchFileImportLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BatchFileImport.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("batchFileImportId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			batchFileImportLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(BatchFileImport.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"batchFileImportId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(batchFileImportLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(BatchFileImport.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("batchFileImportId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<BatchFileImport>() {

				@Override
				public void performAction(BatchFileImport batchFileImport)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, batchFileImport);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(BatchFileImport.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return batchFileImportLocalService.deleteBatchFileImport(
			(BatchFileImport)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return batchFileImportPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the batch file import with the matching UUID and company.
	 *
	 * @param uuid the batch file import's UUID
	 * @param companyId the primary key of the company
	 * @return the matching batch file import
	 * @throws PortalException if a matching batch file import could not be found
	 */
	@Override
	public BatchFileImport getBatchFileImportByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return batchFileImportPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the batch file imports.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.liferay.batch.engine.model.impl.BatchFileImportModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of batch file imports
	 * @param end the upper bound of the range of batch file imports (not inclusive)
	 * @return the range of batch file imports
	 */
	@Override
	public List<BatchFileImport> getBatchFileImports(int start, int end) {
		return batchFileImportPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of batch file imports.
	 *
	 * @return the number of batch file imports
	 */
	@Override
	public int getBatchFileImportsCount() {
		return batchFileImportPersistence.countAll();
	}

	/**
	 * Updates the batch file import in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param batchFileImport the batch file import
	 * @return the batch file import that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public BatchFileImport updateBatchFileImport(
		BatchFileImport batchFileImport) {

		return batchFileImportPersistence.update(batchFileImport);
	}

	/**
	 * Returns the batch file import local service.
	 *
	 * @return the batch file import local service
	 */
	public BatchFileImportLocalService getBatchFileImportLocalService() {
		return batchFileImportLocalService;
	}

	/**
	 * Sets the batch file import local service.
	 *
	 * @param batchFileImportLocalService the batch file import local service
	 */
	public void setBatchFileImportLocalService(
		BatchFileImportLocalService batchFileImportLocalService) {

		this.batchFileImportLocalService = batchFileImportLocalService;
	}

	/**
	 * Returns the batch file import persistence.
	 *
	 * @return the batch file import persistence
	 */
	public BatchFileImportPersistence getBatchFileImportPersistence() {
		return batchFileImportPersistence;
	}

	/**
	 * Sets the batch file import persistence.
	 *
	 * @param batchFileImportPersistence the batch file import persistence
	 */
	public void setBatchFileImportPersistence(
		BatchFileImportPersistence batchFileImportPersistence) {

		this.batchFileImportPersistence = batchFileImportPersistence;
	}

	/**
	 * Returns the batch job execution local service.
	 *
	 * @return the batch job execution local service
	 */
	public com.liferay.batch.engine.service.BatchJobExecutionLocalService
		getBatchJobExecutionLocalService() {

		return batchJobExecutionLocalService;
	}

	/**
	 * Sets the batch job execution local service.
	 *
	 * @param batchJobExecutionLocalService the batch job execution local service
	 */
	public void setBatchJobExecutionLocalService(
		com.liferay.batch.engine.service.BatchJobExecutionLocalService
			batchJobExecutionLocalService) {

		this.batchJobExecutionLocalService = batchJobExecutionLocalService;
	}

	/**
	 * Returns the batch job execution persistence.
	 *
	 * @return the batch job execution persistence
	 */
	public BatchJobExecutionPersistence getBatchJobExecutionPersistence() {
		return batchJobExecutionPersistence;
	}

	/**
	 * Sets the batch job execution persistence.
	 *
	 * @param batchJobExecutionPersistence the batch job execution persistence
	 */
	public void setBatchJobExecutionPersistence(
		BatchJobExecutionPersistence batchJobExecutionPersistence) {

		this.batchJobExecutionPersistence = batchJobExecutionPersistence;
	}

	/**
	 * Returns the batch job instance local service.
	 *
	 * @return the batch job instance local service
	 */
	public com.liferay.batch.engine.service.BatchJobInstanceLocalService
		getBatchJobInstanceLocalService() {

		return batchJobInstanceLocalService;
	}

	/**
	 * Sets the batch job instance local service.
	 *
	 * @param batchJobInstanceLocalService the batch job instance local service
	 */
	public void setBatchJobInstanceLocalService(
		com.liferay.batch.engine.service.BatchJobInstanceLocalService
			batchJobInstanceLocalService) {

		this.batchJobInstanceLocalService = batchJobInstanceLocalService;
	}

	/**
	 * Returns the batch job instance persistence.
	 *
	 * @return the batch job instance persistence
	 */
	public BatchJobInstancePersistence getBatchJobInstancePersistence() {
		return batchJobInstancePersistence;
	}

	/**
	 * Sets the batch job instance persistence.
	 *
	 * @param batchJobInstancePersistence the batch job instance persistence
	 */
	public void setBatchJobInstancePersistence(
		BatchJobInstancePersistence batchJobInstancePersistence) {

		this.batchJobInstancePersistence = batchJobInstancePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.batch.engine.model.BatchFileImport",
			batchFileImportLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.batch.engine.model.BatchFileImport");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return BatchFileImportLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return BatchFileImport.class;
	}

	protected String getModelClassName() {
		return BatchFileImport.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = batchFileImportPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = BatchFileImportLocalService.class)
	protected BatchFileImportLocalService batchFileImportLocalService;

	@BeanReference(type = BatchFileImportPersistence.class)
	protected BatchFileImportPersistence batchFileImportPersistence;

	@BeanReference(
		type = com.liferay.batch.engine.service.BatchJobExecutionLocalService.class
	)
	protected com.liferay.batch.engine.service.BatchJobExecutionLocalService
		batchJobExecutionLocalService;

	@BeanReference(type = BatchJobExecutionPersistence.class)
	protected BatchJobExecutionPersistence batchJobExecutionPersistence;

	@BeanReference(
		type = com.liferay.batch.engine.service.BatchJobInstanceLocalService.class
	)
	protected com.liferay.batch.engine.service.BatchJobInstanceLocalService
		batchJobInstanceLocalService;

	@BeanReference(type = BatchJobInstancePersistence.class)
	protected BatchJobInstancePersistence batchJobInstancePersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}