/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.modern.site.building.fragment.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.modern.site.building.fragment.model.MSBFragmentEntry;
import com.liferay.modern.site.building.fragment.model.MSBFragmentEntryModel;
import com.liferay.modern.site.building.fragment.model.MSBFragmentEntrySoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MSBFragmentEntry service. Represents a row in the &quot;MSBFragmentEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MSBFragmentEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MSBFragmentEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MSBFragmentEntryImpl
 * @see MSBFragmentEntry
 * @see MSBFragmentEntryModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MSBFragmentEntryModelImpl extends BaseModelImpl<MSBFragmentEntry>
	implements MSBFragmentEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a msb fragment entry model instance should use the {@link MSBFragmentEntry} interface instead.
	 */
	public static final String TABLE_NAME = "MSBFragmentEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "msbFragmentEntryId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "msbFragmentCollectionId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "css", Types.VARCHAR },
			{ "html", Types.VARCHAR },
			{ "js", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("msbFragmentEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("msbFragmentCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("css", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("html", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("js", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MSBFragmentEntry (msbFragmentEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,msbFragmentCollectionId LONG,name VARCHAR(75) null,css STRING null,html STRING null,js STRING null)";
	public static final String TABLE_SQL_DROP = "drop table MSBFragmentEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY msbFragmentEntry.name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MSBFragmentEntry.name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.modern.site.building.fragment.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.modern.site.building.fragment.model.MSBFragmentEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.modern.site.building.fragment.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.modern.site.building.fragment.model.MSBFragmentEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.modern.site.building.fragment.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.modern.site.building.fragment.model.MSBFragmentEntry"),
			true);
	public static final long GROUPID_COLUMN_BITMASK = 1L;
	public static final long MSBFRAGMENTCOLLECTIONID_COLUMN_BITMASK = 2L;
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MSBFragmentEntry toModel(MSBFragmentEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MSBFragmentEntry model = new MSBFragmentEntryImpl();

		model.setMsbFragmentEntryId(soapModel.getMsbFragmentEntryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setMsbFragmentCollectionId(soapModel.getMsbFragmentCollectionId());
		model.setName(soapModel.getName());
		model.setCss(soapModel.getCss());
		model.setHtml(soapModel.getHtml());
		model.setJs(soapModel.getJs());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MSBFragmentEntry> toModels(
		MSBFragmentEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MSBFragmentEntry> models = new ArrayList<MSBFragmentEntry>(soapModels.length);

		for (MSBFragmentEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.modern.site.building.fragment.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.modern.site.building.fragment.model.MSBFragmentEntry"));

	public MSBFragmentEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _msbFragmentEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMsbFragmentEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _msbFragmentEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MSBFragmentEntry.class;
	}

	@Override
	public String getModelClassName() {
		return MSBFragmentEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("msbFragmentEntryId", getMsbFragmentEntryId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("msbFragmentCollectionId", getMsbFragmentCollectionId());
		attributes.put("name", getName());
		attributes.put("css", getCss());
		attributes.put("html", getHtml());
		attributes.put("js", getJs());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long msbFragmentEntryId = (Long)attributes.get("msbFragmentEntryId");

		if (msbFragmentEntryId != null) {
			setMsbFragmentEntryId(msbFragmentEntryId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long msbFragmentCollectionId = (Long)attributes.get(
				"msbFragmentCollectionId");

		if (msbFragmentCollectionId != null) {
			setMsbFragmentCollectionId(msbFragmentCollectionId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String css = (String)attributes.get("css");

		if (css != null) {
			setCss(css);
		}

		String html = (String)attributes.get("html");

		if (html != null) {
			setHtml(html);
		}

		String js = (String)attributes.get("js");

		if (js != null) {
			setJs(js);
		}
	}

	@JSON
	@Override
	public long getMsbFragmentEntryId() {
		return _msbFragmentEntryId;
	}

	@Override
	public void setMsbFragmentEntryId(long msbFragmentEntryId) {
		_msbFragmentEntryId = msbFragmentEntryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getMsbFragmentCollectionId() {
		return _msbFragmentCollectionId;
	}

	@Override
	public void setMsbFragmentCollectionId(long msbFragmentCollectionId) {
		_columnBitmask |= MSBFRAGMENTCOLLECTIONID_COLUMN_BITMASK;

		if (!_setOriginalMsbFragmentCollectionId) {
			_setOriginalMsbFragmentCollectionId = true;

			_originalMsbFragmentCollectionId = _msbFragmentCollectionId;
		}

		_msbFragmentCollectionId = msbFragmentCollectionId;
	}

	public long getOriginalMsbFragmentCollectionId() {
		return _originalMsbFragmentCollectionId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask = -1L;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getCss() {
		if (_css == null) {
			return StringPool.BLANK;
		}
		else {
			return _css;
		}
	}

	@Override
	public void setCss(String css) {
		_css = css;
	}

	@JSON
	@Override
	public String getHtml() {
		if (_html == null) {
			return StringPool.BLANK;
		}
		else {
			return _html;
		}
	}

	@Override
	public void setHtml(String html) {
		_html = html;
	}

	@JSON
	@Override
	public String getJs() {
		if (_js == null) {
			return StringPool.BLANK;
		}
		else {
			return _js;
		}
	}

	@Override
	public void setJs(String js) {
		_js = js;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MSBFragmentEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MSBFragmentEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MSBFragmentEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MSBFragmentEntryImpl msbFragmentEntryImpl = new MSBFragmentEntryImpl();

		msbFragmentEntryImpl.setMsbFragmentEntryId(getMsbFragmentEntryId());
		msbFragmentEntryImpl.setGroupId(getGroupId());
		msbFragmentEntryImpl.setCompanyId(getCompanyId());
		msbFragmentEntryImpl.setUserId(getUserId());
		msbFragmentEntryImpl.setUserName(getUserName());
		msbFragmentEntryImpl.setCreateDate(getCreateDate());
		msbFragmentEntryImpl.setModifiedDate(getModifiedDate());
		msbFragmentEntryImpl.setMsbFragmentCollectionId(getMsbFragmentCollectionId());
		msbFragmentEntryImpl.setName(getName());
		msbFragmentEntryImpl.setCss(getCss());
		msbFragmentEntryImpl.setHtml(getHtml());
		msbFragmentEntryImpl.setJs(getJs());

		msbFragmentEntryImpl.resetOriginalValues();

		return msbFragmentEntryImpl;
	}

	@Override
	public int compareTo(MSBFragmentEntry msbFragmentEntry) {
		int value = 0;

		value = getName().compareTo(msbFragmentEntry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MSBFragmentEntry)) {
			return false;
		}

		MSBFragmentEntry msbFragmentEntry = (MSBFragmentEntry)obj;

		long primaryKey = msbFragmentEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MSBFragmentEntryModelImpl msbFragmentEntryModelImpl = this;

		msbFragmentEntryModelImpl._originalGroupId = msbFragmentEntryModelImpl._groupId;

		msbFragmentEntryModelImpl._setOriginalGroupId = false;

		msbFragmentEntryModelImpl._setModifiedDate = false;

		msbFragmentEntryModelImpl._originalMsbFragmentCollectionId = msbFragmentEntryModelImpl._msbFragmentCollectionId;

		msbFragmentEntryModelImpl._setOriginalMsbFragmentCollectionId = false;

		msbFragmentEntryModelImpl._originalName = msbFragmentEntryModelImpl._name;

		msbFragmentEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MSBFragmentEntry> toCacheModel() {
		MSBFragmentEntryCacheModel msbFragmentEntryCacheModel = new MSBFragmentEntryCacheModel();

		msbFragmentEntryCacheModel.msbFragmentEntryId = getMsbFragmentEntryId();

		msbFragmentEntryCacheModel.groupId = getGroupId();

		msbFragmentEntryCacheModel.companyId = getCompanyId();

		msbFragmentEntryCacheModel.userId = getUserId();

		msbFragmentEntryCacheModel.userName = getUserName();

		String userName = msbFragmentEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			msbFragmentEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			msbFragmentEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			msbFragmentEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			msbFragmentEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			msbFragmentEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		msbFragmentEntryCacheModel.msbFragmentCollectionId = getMsbFragmentCollectionId();

		msbFragmentEntryCacheModel.name = getName();

		String name = msbFragmentEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			msbFragmentEntryCacheModel.name = null;
		}

		msbFragmentEntryCacheModel.css = getCss();

		String css = msbFragmentEntryCacheModel.css;

		if ((css != null) && (css.length() == 0)) {
			msbFragmentEntryCacheModel.css = null;
		}

		msbFragmentEntryCacheModel.html = getHtml();

		String html = msbFragmentEntryCacheModel.html;

		if ((html != null) && (html.length() == 0)) {
			msbFragmentEntryCacheModel.html = null;
		}

		msbFragmentEntryCacheModel.js = getJs();

		String js = msbFragmentEntryCacheModel.js;

		if ((js != null) && (js.length() == 0)) {
			msbFragmentEntryCacheModel.js = null;
		}

		return msbFragmentEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{msbFragmentEntryId=");
		sb.append(getMsbFragmentEntryId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", msbFragmentCollectionId=");
		sb.append(getMsbFragmentCollectionId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", css=");
		sb.append(getCss());
		sb.append(", html=");
		sb.append(getHtml());
		sb.append(", js=");
		sb.append(getJs());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.modern.site.building.fragment.model.MSBFragmentEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>msbFragmentEntryId</column-name><column-value><![CDATA[");
		sb.append(getMsbFragmentEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>msbFragmentCollectionId</column-name><column-value><![CDATA[");
		sb.append(getMsbFragmentCollectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>css</column-name><column-value><![CDATA[");
		sb.append(getCss());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>html</column-name><column-value><![CDATA[");
		sb.append(getHtml());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>js</column-name><column-value><![CDATA[");
		sb.append(getJs());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MSBFragmentEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MSBFragmentEntry.class
		};
	private long _msbFragmentEntryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _msbFragmentCollectionId;
	private long _originalMsbFragmentCollectionId;
	private boolean _setOriginalMsbFragmentCollectionId;
	private String _name;
	private String _originalName;
	private String _css;
	private String _html;
	private String _js;
	private long _columnBitmask;
	private MSBFragmentEntry _escapedModel;
}