/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.commerce.product.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the CommerceProductOptionValue service. Represents a row in the &quot;CommerceProductOptionValue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.commerce.product.model.impl.CommerceProductOptionValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.commerce.product.model.impl.CommerceProductOptionValueImpl}.
 * </p>
 *
 * @author Marco Leo
 * @see CommerceProductOptionValue
 * @see com.liferay.commerce.product.model.impl.CommerceProductOptionValueImpl
 * @see com.liferay.commerce.product.model.impl.CommerceProductOptionValueModelImpl
 * @generated
 */
@ProviderType
public interface CommerceProductOptionValueModel extends BaseModel<CommerceProductOptionValue>,
	GroupedModel, LocalizedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a commerce product option value model instance should use the {@link CommerceProductOptionValue} interface instead.
	 */

	/**
	 * Returns the primary key of this commerce product option value.
	 *
	 * @return the primary key of this commerce product option value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this commerce product option value.
	 *
	 * @param primaryKey the primary key of this commerce product option value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the commerce product option value ID of this commerce product option value.
	 *
	 * @return the commerce product option value ID of this commerce product option value
	 */
	public long getCommerceProductOptionValueId();

	/**
	 * Sets the commerce product option value ID of this commerce product option value.
	 *
	 * @param commerceProductOptionValueId the commerce product option value ID of this commerce product option value
	 */
	public void setCommerceProductOptionValueId(
		long commerceProductOptionValueId);

	/**
	 * Returns the group ID of this commerce product option value.
	 *
	 * @return the group ID of this commerce product option value
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this commerce product option value.
	 *
	 * @param groupId the group ID of this commerce product option value
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this commerce product option value.
	 *
	 * @return the company ID of this commerce product option value
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this commerce product option value.
	 *
	 * @param companyId the company ID of this commerce product option value
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this commerce product option value.
	 *
	 * @return the user ID of this commerce product option value
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this commerce product option value.
	 *
	 * @param userId the user ID of this commerce product option value
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this commerce product option value.
	 *
	 * @return the user uuid of this commerce product option value
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this commerce product option value.
	 *
	 * @param userUuid the user uuid of this commerce product option value
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this commerce product option value.
	 *
	 * @return the user name of this commerce product option value
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this commerce product option value.
	 *
	 * @param userName the user name of this commerce product option value
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this commerce product option value.
	 *
	 * @return the create date of this commerce product option value
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this commerce product option value.
	 *
	 * @param createDate the create date of this commerce product option value
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this commerce product option value.
	 *
	 * @return the modified date of this commerce product option value
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this commerce product option value.
	 *
	 * @param modifiedDate the modified date of this commerce product option value
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the commerce product option ID of this commerce product option value.
	 *
	 * @return the commerce product option ID of this commerce product option value
	 */
	public long getCommerceProductOptionId();

	/**
	 * Sets the commerce product option ID of this commerce product option value.
	 *
	 * @param commerceProductOptionId the commerce product option ID of this commerce product option value
	 */
	public void setCommerceProductOptionId(long commerceProductOptionId);

	/**
	 * Returns the title of this commerce product option value.
	 *
	 * @return the title of this commerce product option value
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this commerce product option value in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this commerce product option value
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this commerce product option value in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this commerce product option value. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this commerce product option value in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this commerce product option value
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this commerce product option value in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this commerce product option value
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this commerce product option value.
	 *
	 * @return the locales and localized titles of this commerce product option value
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this commerce product option value.
	 *
	 * @param title the title of this commerce product option value
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this commerce product option value in the language.
	 *
	 * @param title the localized title of this commerce product option value
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this commerce product option value in the language, and sets the default locale.
	 *
	 * @param title the localized title of this commerce product option value
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this commerce product option value from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this commerce product option value
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this commerce product option value from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this commerce product option value
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the priority of this commerce product option value.
	 *
	 * @return the priority of this commerce product option value
	 */
	public int getPriority();

	/**
	 * Sets the priority of this commerce product option value.
	 *
	 * @param priority the priority of this commerce product option value
	 */
	public void setPriority(int priority);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(CommerceProductOptionValue commerceProductOptionValue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CommerceProductOptionValue> toCacheModel();

	@Override
	public CommerceProductOptionValue toEscapedModel();

	@Override
	public CommerceProductOptionValue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}